team/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<team_id>[0-9]+)$', views.TeamPage.as_view(), name='team_page'),
    url(r'^create', views.CreateTeam.as_view(), name='create_team'),
    url(r'^edit$', views.ListTeam.as_view(), name='list_team'),
    url(r'^edit/(?P<team_id>[0-9]+)$', views.EditTeam.as_view(), name='edit_team'),
    url(r'^search$', views.SearchTeam.as_view(), name='search_team'),

]

tournament/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from userprofile.views import MyRegistrationView
from . import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^deneme$', views.deneme, name='deneme'),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('userprofile.urls')),
    url(r'^match/', include('match.urls')),
    url(r'^tourney/', include('tourney.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('registration.auth_urls')),
    # url(r'^', include('django.contrib.auth.urls')),
    url(r'^team/', include('team.urls')),
]

userprofile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<player_id>[0-9]+)$', views.PlayerPage.as_view(), name='player_page'),
    url(r'^edit$', views.EditProfile.as_view(), name='edit_profile'),
    url(r'^edit/(?P<user_id>[0-9]+)$', views.EditProfile.as_view(), name='edit_profile_id'),
    url(r'^offer$', views.TransferOfferView.as_view(), name='transfer_offer'),
    url(r'^offer/(?P<offer_id>[0-9]+)$', views.TransferOfferAnswer.as_view(), name='offer_answer'),
    url(r'^search$', views.SearchUser.as_view(), name='search_user'),

]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from userprofile.choices import *
from team.models import Team


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    position = models.IntegerField(choices=POSITION, default=0)
    origin_id = models.CharField(max_length=30)
    user_type = models.IntegerField(choices=USER_TYPE, default=3)
    team = models.ForeignKey(Team, null=True)

    def __str__(self):
        return self.origin_id

team/forms.py
from django import forms
from . import models
from userprofile.models import UserProfile


class MyModelChoiceField(forms.ModelChoiceField):
    def to_python(self, value):
        return UserProfile.objects.get(pk=value)


class TeamForm(forms.ModelForm):

    players = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all())
    captain = forms.ModelChoiceField(queryset=UserProfile.objects.all(), empty_label=None, widget=forms.Select(choices=[]))
    # captain = forms.ChoiceField()

    class Meta:
        model = models.Team
        fields = ['name', 'cash']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['players'].widget.attrs['class'] = 'select2'
        self.fields['players'].widget.attrs['data-placeholder'] = 'Select players'

        self.fields['captain'].widget.attrs['class'] = 'select2'
        self.fields['captain'].widget.attrs['data-placeholder'] = 'Select Captain'


class EditTeamForm(TeamForm):
    captain = MyModelChoiceField(required=False, queryset=None, empty_label=None)

    def __init__(self, *args, **kwargs):
        team_id = kwargs.pop('team_id', None)
        super().__init__(*args, **kwargs)
        self.fields['captain'].widget.attrs['class'] = 'select2'
        self.fields['captain'].widget.attrs['data-placeholder'] = 'Select Captain'
        if team_id:
            self.fields['captain'].queryset = UserProfile.objects.filter(team_id=team_id)

userprofile/forms.py
from django import forms
from django.forms import ModelForm
from registration.forms import RegistrationFormUniqueEmail
from userprofile.choices import *
from django.contrib.auth.models import User


class UserProfileRegisterForm(RegistrationFormUniqueEmail):
    position = forms.ChoiceField(label="Position", initial=1, widget=forms.Select(), required=True, choices=POSITION)
    origin_id = forms.CharField()
    # user_type = forms.ChoiceField(label="User Type", initial=3, widget=forms.Select(), required=True, choices=USER_TYPE)


class UserProfileForm(ModelForm):
    position = forms.ChoiceField(label="Position", initial=1, widget=forms.Select(), choices=POSITION)
    origin_id = forms.CharField()
    # password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False


class UserProfileFormAdmin(UserProfileForm):
    user_type = forms.ChoiceField(label="User Type", initial=3, widget=forms.Select(), choices=USER_TYPE)

    class Meta(UserProfileForm.Meta):
        UserProfileForm.Meta.fields += ['is_active', 'date_joined']

userprofile/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.db.models import Q

from tournament.forms import TransferOfferForm
from tournament.models import TransferOffer, TeamCaptains, PlayerTransfers
from .forms import *
from .models import *
from registration.backends.default.views import RegistrationView


# Create your views here.

class MyRegistrationView(RegistrationView):

    form_class = UserProfileRegisterForm

    def register(self, form_class):
        new_user = super(MyRegistrationView, self).register(form_class)
        user_profile = UserProfile()
        user_profile.user = new_user
        user_profile.position = form_class.cleaned_data['position']
        user_profile.origin_id = form_class.cleaned_data['origin_id']
        user_profile.user_type = 3
        user_profile.save()
        return user_profile


class EditProfile(LoginRequiredMixin, View):

    def get(self, request, user_id=0):
        current_user_profile = UserProfile.objects.get(user_id=request.user.pk)
        user_id = int(user_id)

        user_profile = {}
        if user_id == 0:
            if current_user_profile.user_type == ADMIN:
                user_profiles = UserProfile.objects.all()
                return render(request, "userprofile/list_users.html", {'user_profiles': user_profiles})
            else:
                return redirect('edit_profile_id', user_id=request.user.pk)
        elif current_user_profile.user_type == ADMIN or user_id == request.user.pk:
            user_profile = UserProfile.objects.get(user_id=user_id)
        else:
            return render(request, 'tournament/index.html', {'info_message': 'Access Denied'})

        form_variables = user_profile.__dict__
        form_variables.update(user_profile.user.__dict__)
        del form_variables["password"]

        up_form = UserProfileFormAdmin(initial=form_variables) if current_user_profile.user_type == ADMIN else UserProfileForm(initial=form_variables)
        context = {'UserProfileForm': up_form, 'user_profile': user_profile}
        return render(request, 'userprofile/edit_profile.html', context)

    def post(self, request, user_id=0):

        current_user_profile = UserProfile.objects.get(user_id=request.user.pk)
        if user_id == 0:
            return redirect('edit_profile_id', user_id=request.user.pk)
        elif current_user_profile.user_type == ADMIN:
            user_profile = UserProfile.objects.get(user_id=user_id)
        elif current_user_profile.user_id != request.user.pk:
            return render(request, 'tournament/index.html', {'info_message': 'Access Denied!'})
        else:
            user_profile = UserProfile.objects.get(user_id=request.user.pk)

        form = UserProfileFormAdmin(request.POST, instance=user_profile.user) if current_user_profile.user_type == ADMIN else UserProfileForm(request.POST, instance=user_profile.user)
        if form.is_valid():
            user_profile.user.username = form.cleaned_data['username']
            user_profile.user.first_name = form.cleaned_data['first_name']
            user_profile.user.last_name = form.cleaned_data['last_name']
            user_profile.user.email = form.cleaned_data['email']
            user_profile.position = form.cleaned_data['position']
            user_profile.origin_id = form.cleaned_data['origin_id']
            if current_user_profile.user_type == ADMIN:
                user_profile.user_type = form.cleaned_data['user_type']
                user_profile.user.is_active = form.cleaned_data['is_active']
                user_profile.user.date_joined = form.cleaned_data['date_joined']
            user_profile.save()
            user_profile.user.save()

            return redirect('edit_profile_id', user_id=user_id)
        else:
            return render(request, 'userprofile/edit_profile.html', {'UserProfileForm': form})


class PlayerPage(View):
    def get(self, request, player_id, info_message=''):
        if request.user.is_authenticated():
            cup = UserProfile.objects.get(user_id=request.user.pk) # cup=current_user_profile
        else:
            cup = {}
        cansee_offers = True if int(player_id) == request.user.pk else False
        offers = TransferOffer.objects.filter(receiver_id=request.user.pk, is_answered=False)
        player_transfers = PlayerTransfers.objects.filter(player_id=cup.user_id)
        context = {
            'offers': offers,
            'cansee_offers': cansee_offers,
            'cup': cup,
            'user_profile': UserProfile.objects.get(user_id=player_id),
            'player_transfers': player_transfers,
        }
        if info_message:
            context['info_message'] = info_message
        return render(request, "userprofile/player_page.html", context)


class TransferOfferView(LoginRequiredMixin, View):
    def get(self, request):
        current_user_profile = UserProfile.objects.get(user_id=request.user.pk)
        if current_user_profile.user_type != ADMIN and current_user_profile.user_type != CAPTAIN:
            return render(request, 'tournament/index.html', {'info_message': 'Access Denied'})

        form = TransferOfferForm(for_admin=True) if current_user_profile.user_type == ADMIN else TransferOfferForm()
        context = {
            'form': form
        }
        return render(request, "userprofile/transfer_offer.html", context)

    def post(self, request):
        current_user_profile = UserProfile.objects.get(user_id=request.user.pk)
        if current_user_profile.user_type != ADMIN and current_user_profile.user_type != CAPTAIN:
            return render(request, 'tournament/index.html', {'info_message': 'Access Denied'})

        form = TransferOfferForm(request.POST, for_admin=True) if current_user_profile.user_type == ADMIN else TransferOfferForm(request.POST, )
        if form.is_valid():
            if current_user_profile.user_type == ADMIN:
                sender_team = form.cleaned_data['sender_team']
            elif current_user_profile.user_type == CAPTAIN:
                sender_team = current_user_profile.team
            receiver = form.cleaned_data['receiver']
            to = TransferOffer(sender_team=sender_team, receiver=receiver)
            to.save()

            return render(request, "userprofile/transfer_offer.html", {'form': form, 'info_message': 'Offer sent'})
        else:
            return render(request, "userprofile/transfer_offer.html", {'form': form})


class TransferOfferAnswer(LoginRequiredMixin, View):
    def get(self, request, offer_id):
        current_user_profile = UserProfile.objects.get(user_id=request.user.pk)
        offer = TransferOffer.objects.get(pk=offer_id)

        if offer.receiver == current_user_profile:
            offer.is_answered = True
            if int(request.GET['accepted']):
                current_user_profile.team_id = offer.sender_team_id
                if current_user_profile.user_type != ADMIN:
                    current_user_profile.user_type = PLAYER
                current_user_profile.save()

                if current_user_profile.user_type == CAPTAIN:
                    tc = TeamCaptains.objects.get(player_id=current_user_profile.user_id)
                    tc.delete()
                    tc.save()

                transfer = PlayerTransfers()
                transfer.player = current_user_profile
                transfer.team = offer.sender_team
                transfer.save()

                offer.is_accepted = True
                offer.delete()
                return PlayerPage().get(request=request, player_id=request.user.pk, info_message='Offer Accepted')
            else:
                offer.is_accepted = False
                offer.delete()
                return PlayerPage().get(request=request, player_id=request.user.pk, info_message='Offer Rejected')
        else:
            return render('tournament/index.html', info_message='Access Denied!')


class SearchUser(View):
    def get(self, request):
        q = request.GET['q']
        user_results = User.objects.filter(Q(username__icontains=q))

        user_profile_results = []
        for user in user_results:
            print(user.username)
            user_profile_results.append(UserProfile.objects.get(user_id=user.pk))

        context = {'user_profiles': user_profile_results}

        return render(request, 'userprofile/list_users.html', context)

userprofile/templates/userprofile/edit_profile.html
{% extends "box_content.html" %}

{% block title %} User Profile {% endblock %}
{% block meta %}  {% endblock %}

{% block box_content %}

    <!-- form start -->
    <div class="box-body">
        {% if auth_user_profile.user_id == user_profile.user_id %}
        <a class="btn btn-block btn-primary" href="{% url 'auth_password_change' %}">Change Password</a>
        {% endif %}
    </div>
    <form class="form-horizontal" method="post">
      <div class="box-body">


        {% load widget_tweaks %}
        {% for field in UserProfileForm %}
        <div class="form-group">
            {{ field.errors }}
            <label class="col-sm-2 control-label">{{ field.label_tag }}</label>

            <div class="col-sm-10">
                {% if field.name != 'is_active' %}
                    {% render_field field class+="form-control" %}
                {% else %}
                    {{ field }}
                {% endif %}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>

        </div>
        {% endfor %}

        {% csrf_token %}
      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-info btn-block">Submit</button>
      </div>
      <!-- /.box-footer -->
    </form>

{% endblock %}

{% block include_js %}
    {% include "info_modal_script.html" with error_message=error_message %}
{% endblock %}

userprofile/templates/userprofile/list_users.html
{% extends "box_content.html" %}

{% block title %} User Profile {% endblock %}
{% block meta %}  {% endblock %}
{% load widget_tweaks %}
{% block box_content %}

<div class="list-group">
    {% for user_profile in user_profiles %}
    <a href="{% url 'player_page' player_id=user_profile.user_id %}" class="text-info list-group-item">
        <h5 class="text-primary lit-group-item-heading">{{ user_profile.user.username }}
            <small class="small">{{ user_profile.get_position_display }}</small>
        </h5>
        <p class="text-info list-group-item-text">
            <span class="label label-info">{{ user_profile.team.name }}</span>
        </p>
    </a>
    {% endfor %}
</div>

{% endblock %}

{% load staticfiles%}
{% block include_css %}
<link rel="stylesheet" href="{% static 'tournament/bower_components/select2/dist/css/select2.min.css' %} ">
{% endblock %}
{% block include_js %}
<script src="{% static 'tournament/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<script>
        $("#id_players").select2();

</script>
    {% include "info_modal_script.html" with error_message=error_message %}

{% endblock %}

userprofile/templates/userprofile/transfer_offer.html
{% extends "box_content.html" %}

{% block title %} User Profile {% endblock %}
{% block meta %}  {% endblock %}

{% block box_content %}

    <!-- form start -->
    <form id="transfer-form" class="form-horizontal" method="post">
      <div class="box-body">


        {% load widget_tweaks %}
        {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            <label class="col-sm-2 control-label">{{ field.label_tag }}</label>

            <div class="col-sm-10">
                {% if field.name != 'is_active' %}
                    {% render_field field class+="form-control" %}
                {% else %}
                    {{ field }}
                {% endif %}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>

        </div>
        {% endfor %}

        {% csrf_token %}
      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-info btn-block">Submit</button>
      </div>
      <!-- /.box-footer -->
    </form>

{% endblock %}

{% load staticfiles%}
{% block include_css %}
    <link rel="stylesheet" href="{% static 'tournament/bower_components/select2/dist/css/select2.min.css' %} ">
{% endblock %}
{% block include_js %}
    <script src="{% static 'tournament/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
    <script>
        $("#transfer-form select").select2();
    </script>
    {% include "info_modal_script.html" with error_message=error_message %}
{% endblock %}