match/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<match_id>[0-9]+)$', views.MatchPage.as_view(), name='match_page'),
    url(r'^edit/(?P<match_id>[0-9]+)$', views.EditMatch.as_view(), name='edit_match'),
]

team/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<team_id>[0-9]+)$', views.TeamPage.as_view(), name='team_page'),
    url(r'^create', views.CreateTeam.as_view(), name='create_team'),
    url(r'^edit$', views.ListTeam.as_view(), name='list_team'),
    url(r'^edit/(?P<team_id>[0-9]+)$', views.EditTeam.as_view(), name='edit_team'),
    url(r'^search$', views.SearchTeam.as_view(), name='search_team'),

]

tournament/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from userprofile.views import MyRegistrationView
from . import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^deneme$', views.deneme, name='deneme'),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('userprofile.urls')),
    url(r'^match/', include('match.urls')),
    url(r'^tourney/', include('tourney.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('registration.auth_urls')),
    # url(r'^', include('django.contrib.auth.urls')),
    url(r'^team/', include('team.urls')),
]

match/forms.py
from django import forms
from django.forms import ModelForm

from team.models import Team
from .models import Match
from userprofile.models import UserProfile


class MatchForm(ModelForm):
    squad_home = forms.ModelMultipleChoiceField(queryset=None)
    squad_away = forms.ModelMultipleChoiceField(queryset=None)
    ss1 = forms.FileField(required=False)
    ss2 = forms.FileField(required=False)
    ss3 = forms.FileField(required=False)
    ss4 = forms.FileField(required=False)
    ss5 = forms.FileField(required=False)

    class Meta:
        model = Match
        fields = ['squad_home', 'squad_away', 'result_home', 'result_away', 'played']

    def __init__(self, *args, **kwargs):
        home_id = kwargs.pop('home_id', None)
        away_id = kwargs.pop('away_id', None)
        super().__init__(*args, **kwargs)
        team1 = Team.objects.get(pk=home_id)
        team2 = Team.objects.get(pk=away_id)

        # self.fields["result_home"].initial = None
        # self.fields["result_away"].initial = None

        self.fields["squad_home"].label = "Squad " + team1.name
        self.fields["squad_away"].label = "Squad " + team2.name

        self.fields["result_home"].label = "Result " + team1.name
        self.fields["result_away"].label = "Result " + team2.name

        self.fields["squad_home"].queryset = UserProfile.objects.filter(team_id=home_id)
        self.fields["squad_away"].queryset = UserProfile.objects.filter(team_id=away_id)

        self.fields['squad_home'].widget.attrs['class'] = 'select2'
        self.fields['squad_home'].widget.attrs['data-placeholder'] = 'Select players'

        self.fields['squad_away'].widget.attrs['class'] = 'select2'
        self.fields['squad_away'].widget.attrs['data-placeholder'] = 'Select players'

    def clean(self):
        super().clean()
        self.cleaned_data['squad_home'] = self.data['squad_home']
        self.cleaned_data['squad_away'] = self.data['squad_away']
        return self.cleaned_data

team/forms.py
from django import forms
from . import models
from userprofile.models import UserProfile


class MyModelChoiceField(forms.ModelChoiceField):
    def to_python(self, value):
        return UserProfile.objects.get(pk=value)


class TeamForm(forms.ModelForm):

    players = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all())
    captain = forms.ModelChoiceField(queryset=UserProfile.objects.all(), empty_label=None, widget=forms.Select(choices=[]))
    # captain = forms.ChoiceField()

    class Meta:
        model = models.Team
        fields = ['name', 'cash']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['players'].widget.attrs['class'] = 'select2'
        self.fields['players'].widget.attrs['data-placeholder'] = 'Select players'

        self.fields['captain'].widget.attrs['class'] = 'select2'
        self.fields['captain'].widget.attrs['data-placeholder'] = 'Select Captain'


class EditTeamForm(TeamForm):
    captain = MyModelChoiceField(required=False, queryset=None, empty_label=None)

    def __init__(self, *args, **kwargs):
        team_id = kwargs.pop('team_id', None)
        super().__init__(*args, **kwargs)
        self.fields['captain'].widget.attrs['class'] = 'select2'
        self.fields['captain'].widget.attrs['data-placeholder'] = 'Select Captain'
        if team_id:
            self.fields['captain'].queryset = UserProfile.objects.filter(team_id=team_id)

match/views.py
import base64
import json

from django.db.models.query_utils import Q
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from match.models import Match
from tournament.models import TeamCaptains, TourneyMatches, MatchPlayers
from tournament.forms import MatchPlayersForm
from tourney.models import League
from userprofile.models import UserProfile
from . import forms
from . import models
# Create your views here.


class MatchPage(View):
    def get(self, request, match_id):
        match = Match.objects.get(pk=match_id)
        if match.squad_home:
            match.squad_home = [UserProfile.objects.get(user_id=int(pid)) for pid in match.squad_home.split(',')]
        if match.squad_away:
            match.squad_away = [UserProfile.objects.get(user_id=int(pid)) for pid in match.squad_away.split(',')]
        return render(request, 'match/match_page.html', {'match': match})


class EditMatch(View):
    def get(self, request, match_id, info_message=''):
        if not request.GET.get('for_team'):
            request.GET = request.GET.copy()
            request.GET['for_team'] = 'home'

        cup = UserProfile.objects.get(user_id=request.user.pk)
        match = models.Match.objects.get(pk=match_id)

        captain_home = TeamCaptains.objects.get(team_id=match.home.pk).player_id
        captain_away = TeamCaptains.objects.get(team_id=match.away.pk).player_id

        if not cup.user_type == 1 and not (request.user.pk == captain_home or request.user.pk == captain_away):
            return redirect('index')

        initial = match.__dict__
        if match.squad_home:
            squad_home_list = match.squad_home.split(',')
            initial['squad_home'] = squad_home_list
        if match.squad_home:
            squad_away_list = match.squad_away.split(',')
            initial['squad_away'] = squad_away_list
        form = forms.MatchForm(home_id=match.home.pk, away_id=match.away.pk, initial=initial)

        if not (request.user.pk == captain_home or request.user.pk == captain_away):
            del form.fields["ss1"]
            del form.fields["ss2"]
            del form.fields["ss3"]
            del form.fields["ss4"]
            del form.fields["ss5"]

        screenshots = []
        if cup.team == match.home:
            screenshots.append(match.ss1_home) if match.ss1_home else screenshots.append('')
            screenshots.append(match.ss2_home) if match.ss2_home else screenshots.append('')
            screenshots.append(match.ss3_home) if match.ss3_home else screenshots.append('')
            screenshots.append(match.ss4_home) if match.ss4_home else screenshots.append('')
            screenshots.append(match.ss5_home) if match.ss5_home else screenshots.append('')
        elif cup.team == match.home:
            screenshots.append(match.ss1_away) if match.ss1_away else screenshots.append('')
            screenshots.append(match.ss2_away) if match.ss2_away else screenshots.append('')
            screenshots.append(match.ss3_away) if match.ss3_away else screenshots.append('')
            screenshots.append(match.ss4_away) if match.ss4_away else screenshots.append('')
            screenshots.append(match.ss5_away) if match.ss5_away else screenshots.append('')

        if cup.pk == captain_home:
            match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=1))
        elif cup.pk == captain_away:
            match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=2))
        elif cup.user_type == 1:
            if request.GET['for_team'] == 'home':
                match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=1))
            elif request.GET['for_team'] == 'away':
                match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=2))

        match_player_forms = []
        for match_player in match_players:
            match_player_forms.append(MatchPlayersForm(match_player_id=match_player.pk))

        context = {
            'form': form,
            'screenshots': screenshots,
            'match_player_form': MatchPlayersForm(),
            'match_player_forms': match_player_forms,
            'match': match,
        }
        if info_message:
            context['info_message'] = info_message
        return render(request, 'match/edit_match.html', context)

    def post(self, request, match_id):
         if not request.GET.get('for_team'):
            request.GET = request.GET.copy()
            request.GET['for_team'] = 'home'

        cup = UserProfile.objects.get(user_id=request.user.pk)
        match = models.Match.objects.get(pk=match_id)
        request.POST = request.POST.copy()

        if match.played:
            return self.get(request, match_id, 'This match can not be edited since it is marked as played by Admin')

        request.POST['squad_home'] = ','.join(request.POST.getlist('squad_home'))
        request.POST['squad_away'] = ','.join(request.POST.getlist('squad_away'))

        captain_home = TeamCaptains.objects.get(team_id=match.home.pk).player_id
        captain_away = TeamCaptains.objects.get(team_id=match.away.pk).player_id
        if not (request.user.pk == captain_home or request.user.pk == captain_away) and not cup.user_type == 1:
            return redirect('index')

        form = forms.MatchForm(request.POST, request.FILES, home_id=match.home.pk, away_id=match.away.pk)

        form.is_valid()
        ss1 = "data:image/jpg;base64," + base64.b64encode(form.cleaned_data['ss1'].read()).decode('ascii') if form.cleaned_data['ss1'] else ''
        ss2 = "data:image/jpg;base64," + base64.b64encode(form.cleaned_data['ss2'].read()).decode('ascii') if form.cleaned_data['ss2'] else ''
        ss3 = "data:image/jpg;base64," + base64.b64encode(form.cleaned_data['ss3'].read()).decode('ascii') if form.cleaned_data['ss3'] else ''
        ss4 = "data:image/jpg;base64," + base64.b64encode(form.cleaned_data['ss4'].read()).decode('ascii') if form.cleaned_data['ss4'] else ''
        ss5 = "data:image/jpg;base64," + base64.b64encode(form.cleaned_data['ss5'].read()).decode('ascii') if form.cleaned_data['ss5'] else ''

        match.squad_home = form.cleaned_data['squad_home']
        match.squad_away = form.cleaned_data['squad_away']

        match.result_home = form.cleaned_data['result_home']
        match.result_away = form.cleaned_data['result_away']

        if cup.team == match.home:
            match.ss1_home = ss1 if ss1 else match.ss1_home
            match.ss2_home = ss2 if ss2 else match.ss2_home
            match.ss3_home = ss3 if ss3 else match.ss3_home
            match.ss4_home = ss4 if ss4 else match.ss4_home
            match.ss5_home = ss5 if ss5 else match.ss5_home
        elif cup.team == match.away:
            match.ss1_away = ss1 if ss1 else match.ss1_away
            match.ss2_away = ss2 if ss2 else match.ss2_away
            match.ss3_away = ss3 if ss3 else match.ss3_away
            match.ss4_away = ss4 if ss4 else match.ss4_away
            match.ss5_away = ss5 if ss5 else match.ss5_away

        if cup.user_type == 1:
            match.played = form.cleaned_data["played"]

        match_player_strings = request.POST['match_players'].split(',')

        # creating MatchPlayers entries fo database
        player_dicts = []
        for string in match_player_strings:
            if string == '':
                continue
            elif string[0] == '&':
                string = string[1:]
            player_dict = {}
            splitted = string.split('&')
            for kv in splitted:
                if kv == '':
                    continue
                key, value = kv.split('=')
                player_dict[key] = value

            player_dicts.append(player_dict)

        if cup.pk == captain_home:
            match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=1))
        elif cup.pk == captain_away:
            match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=2))
        elif cup.user_type == 1:
            if request.GET['for_team'] == 'home':
                match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=1))
            elif request.GET['for_team'] == 'away':
                match_players = MatchPlayers.objects.filter(Q(match=match) & Q(team=2))

        match_players = list(match_players)
        while len(match_players) != len(player_dicts):
            if len(match_players) < len(player_dicts):
                match_players.append(MatchPlayers())
            else:
                match_players[0].delete()
                match_players = match_players[1:]

        for i, player_dict in enumerate(player_dicts):
            mpform = MatchPlayersForm(player_dict)
            if mpform.is_valid():
                target_match_player = match_players[i]
                target_match_player.match = match
                target_match_player.player = mpform.cleaned_data['player']
                target_match_player.yellow_card = mpform.cleaned_data['yellow_card']
                target_match_player.red_card = mpform.cleaned_data['red_card']
                target_match_player.position = mpform.cleaned_data['position']
                target_match_player.goal = mpform.cleaned_data['goal']
                target_match_player.mvp = mpform.cleaned_data['mvp']
                if cup.pk == captain_home:
                    target_match_player.team = target_match_player.HOME
                elif cup.pk == captain_home:
                    target_match_player.team = target_match_player.AWAY
                elif cup.user_type == 1:
                    if request.GET['for_team'] == 'home':
                        target_match_player.team = target_match_player.HOME
                    elif request.GET['for_team'] == 'away':
                        target_match_player.team = target_match_player.AWAY
                target_match_player.save()
            else:

match/templates/match/edit_match.html
{% extends "box_content.html" %}

{% block title %} User Profile {% endblock %}
{% block meta %}  {% endblock %}
{% load widget_tweaks %}
{% block box_content %}
<!-- form start -->
    <div class="box-body">
        {% if auth_user_profile.user_type == 1 %}
        <div style="width:50%;margin:auto;padding:10px">
            <a href="{% url 'edit_match' match_id=match.pk %}?for_team=home" class="btn btn-primary">Edit For Home</a>
            <a href="{% url 'edit_match' match_id=match.pk %}?for_team=away" class="btn btn-primary pull-right">Edit For Away</a>
        </div>
        {% endif %}

        <div id="match_player_forms" class="col-sm-10 col-sm-offset-2">
            <div id="match_player_forms_inner_content">

                {% for match_player_form in match_player_forms %}
                <div>
                    <form class="form-horizontal" action="">
                        {{ match_player_form }}
                        <input type="text" name="spl" value="0" hidden>
                    <i onclick="$(this).parent().parent().remove()" class="btn fa fa-close"></i>
                    </form>
                </div>
                {% endfor  %}

            </div>
            <style>
                #match_player_forms{
                    border:1px dotted black;
                    border-radius:10px;
                    margin-bottom:20px;
                }
                #match_player_forms input{
                    max-width:50px;
                }
                #match_player_forms div{
                    padding:17px 0px;
                }
            </style>
            <div style="margin:auto;width:60%">
                <button onclick="addPlayer();" class="btn btn-info pull-right">Add Player</button>
            </div>
        </div>
        <hr>
        <form id="create_match_form" onsubmit="submit_form()" class="form-horizontal" method="post" enctype="multipart/form-data"> {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            <label class="col-sm-2 control-label">{{ field.label_tag }}</label>

            <div class="col-sm-10">
                {% if field.name != 'played' %}
                    {% render_field field class+="form-control" %}
                {% else %}
                    {{ field }}
                {% endif %}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>

        </div>

        {% endfor %}
        <input type="text" name="match_players" id="id_match_players" hidden>
        <hr/>

        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <!--<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>-->
            <!--<li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>-->
            <!--<li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>-->
            <!--<li data-target="#carousel-example-generic" data-slide-to="3" class=""></li>-->
            <!--<li data-target="#carousel-example-generic" data-slide-to="4" class=""></li>-->
        </ol>
            <div class="carousel-inner">
                {% for ss in screenshots %}
                <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                    <div class="text-center">
                        <img style="max-width:100%;min-height:400px" src="{{ ss }}" alt="First slide">
                    </div>

                    <div class="carousel-caption">
                        First Slide
                    </div>
                </div>
                {% endfor %}
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="fa fa-angle-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="fa fa-angle-right"></span>
            </a>
        </div>

    </div>
    <div class="box-footer">
        <button type="submit" class="btn btn-info btn-block">Submit</button>
    </div>
    </form>
    <!-- /.box-footer -->
<!--</form>-->
        <div id="match_player_form" class="hidden">
            <div>
                <form class="form-horizontal" action="">
                    {{ match_player_form }}
                    <input type="text" name="spl" value="0" hidden>
                <i onclick="$(this).parent().parent().remove()" class="btn fa fa-close"></i>
                </form>
            </div>
        </div>

{% endblock %}

{% load staticfiles%}
{% block include_css %}
<link rel="stylesheet" href="{% static 'tournament/bower_components/select2/dist/css/select2.min.css' %} ">
{% endblock %}
{% block include_js %}
<script src="{% static 'tournament/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<script>
        function getSelectedOps(select_id){
            select = document.getElementById(select_id);
            var ops = select.options;
            var res = "";
            for(i = 0;i < ops.length;i++){
                if(ops[i].selected)
                res += '<option value="' + ops[i].value + '">' + ops[i].text + "</option>\n"
            }
            return res;
        }

        function addPlayer(){
            $('#match_player_forms_inner_content').append($('#match_player_form').html())
            $("#match_player_forms_inner_content form select").select2();
        }

        function serialize_match_player_forms(){
            var res = $('#match_player_forms_inner_content div form').serialize().split("&spl=0")
            return res;
        }

        function submit_form(){
            //$('#create_match_form').submit(function() {
                $("#id_match_players").val(serialize_match_player_forms);
                return true;
            //});
        }

        $("#id_players").change(function(){
            $("#id_captain").html(getSelectedOps("id_players"));
        });
        $("#create_match_form select").select2();
        $("#match_player_forms_inner_content form select").select2();

</script>
{% include "info_modal_script.html" with error_message=error_message %}
{% endblock %}